import random

def quotes_generator():
    quotes = [
        "Take care of your body. It’s the only place you have to live. – Jim Rohn",
        "Health is not valued till sickness comes. – Thomas Fuller",
        "The greatest wealth is health. – Virgil",
        "A healthy outside starts from the inside. – Robert Urich",
        "Your body deserves the best. – Anonymous",
        "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. – Buddha",
        "An apple a day keeps the doctor away. – Proverb",
        "Exercise is a celebration of what your body can do, not a punishment for what you ate. – Anonymous",
        "The human body is the best picture of the human soul. – Ludwig Wittgenstein",
        "To enjoy the glow of good health, you must exercise. – Gene Tunney",
        "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
        "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
        "Your health is an investment, not an expense. – Anonymous",
        "If you think wellness is expensive, try illness. – Anonymous",
        "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
        "Health is a state of complete harmony of the body, mind, and spirit. – B.K.S. Iyengar",
        "The only bad workout is the one that didn’t happen. – Anonymous",
        "Health is the crown on the well person’s head that only the ill person can see. – Robin Sharma",
        "Don’t count the days. Make the days count. – Muhammad Ali",
        "Wellness is the natural state of my body. – Anonymous",
        "A healthy mind resides in a healthy body. – Anonymous",
        "Your diet is a bank account. Good food choices are good investments. – Bethenny Frankel",
        "Every human being is the author of his own health or disease. – Buddha",
        "If you keep good food in your fridge, you will eat good food. – Errick McAdams",
        "It is health that is real wealth and not pieces of gold and silver. – Mahatma Gandhi",
        "The secret of getting ahead is getting started. – Mark Twain",
        "Eat to live, don’t live to eat. – Benjamin Franklin",
        "Good health and good sense are two of life’s greatest blessings. – Publilius Syrus",
        "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear. – Buddha",
        "Wellness is not just about eating healthy and exercising. It’s also about having a positive attitude, being happy, and finding balance in life. – Anonymous",
        "The more you sweat in practice, the less you bleed in battle. – Anonymous",
        "The first wealth is health. – Ralph Waldo Emerson",
        "Eat food, not much, mostly plants. – Michael Pollan",
        "A good laugh and a long sleep are the two best cures for anything. – Irish Proverb",
        "Prevention is better than cure. – Desiderius Erasmus",
        "Healthy habits are learned in the same way as unhealthy ones – through practice. – Wayne Dyer",
        "Your health is a reflection of how well you take care of yourself. – Anonymous",
        "Take care of your body, it’s the only place you have to live. – Jim Rohn",
        "The best way to predict your future is to create it. – Peter Drucker",
        "Happiness is the highest form of health. – Dalai Lama",
        "Fitness is not about being better than someone else; it’s about being better than you used to be. – Khloe Kardashian",
        "The body achieves what the mind believes. – Anonymous",
        "Let food be thy medicine and medicine be thy food. – Hippocrates",
        "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
        "A healthy lifestyle is not just about eating right and exercising; it’s about feeling good and being happy. – Anonymous",
        "The way you get meaning into your life is to devote yourself to loving others, devote yourself to your community around you, and devote yourself to creating something that gives you purpose and meaning. – Mitch Albom",
        "You are what you eat. – Anonymous",
        "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend. Non-attachment is the greatest joy. – Lao Tzu",
        "Energy and persistence conquer all things. – Benjamin Franklin",
        "Healthy does not mean starving yourself ever. Healthy means eating the right food in the right amount. – Anonymous",
        "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity. – John F. Kennedy",
        "Good health is a blessing that cannot be bought with money. – Anonymous",
        "The best project you’ll ever work on is you. – Anonymous",
        "You don’t have to be perfect to be amazing. – Anonymous",
        "A healthy diet is a good start, but exercise is the key to good health. – Anonymous",
        "To love oneself is the beginning of a lifelong romance. – Oscar Wilde",
        "A healthy outside starts from the inside. – Anonymous",
        "Wellness is a journey, not a destination. – Anonymous",
        "The mind is a powerful thing. It can heal or harm the body. – Anonymous",
        "Every day is a chance to be healthier. – Anonymous",
        "Your health is a reflection of how you live your life. – Anonymous",
        "Self-care is giving the world the best of you instead of what’s left of you. – Katie Reed",
        "Exercise is a celebration of what your body can do, not a punishment for what you ate. – Anonymous",
        "It’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
        "Eat to live, don’t live to eat. – Benjamin Franklin",
        "Take care of your body; it’s the only place you have to live. – Jim Rohn",
        "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
        "Health is the first wealth. – Ralph Waldo Emerson",
        "The body achieves what the mind believes. – Anonymous",
        "Health is not merely the absence of disease; it’s the presence of vitality. – Anonymous",
        "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
        "Health is a state of complete harmony of the body, mind, and spirit. – B.K.S. Iyengar",
        "Health is not valued till sickness comes. – Thomas Fuller",
        "The greatest wealth is health. – Virgil",
        "An apple a day keeps the doctor away. – Proverb",
        "Exercise is a celebration of what your body can do, not a punishment for what you ate. – Anonymous",
        "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
        "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
        "Your health is an investment, not an expense. – Anonymous",
        "If you think wellness is expensive, try illness. – Anonymous",
        "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
        "Health is a state of complete harmony of the body, mind, and spirit. – B.K.S. Iyengar"
    ]
    quote = random.randint(0,82)
    return quotes[quote]